name: Unity Tests

on:
  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - empty-unity-project
        testMode:
          - playmode
          - editmode

    steps:
      - name: Checkout pulse repo
        uses: actions/checkout@v4

      - name: Check files
        run: ls

      - name: Clone empty Unity project
        run: |
          git clone https://DanilChizhikov:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/DanilChizhikov/empty-unity-project.git empty-unity-project

      - name: Copy logging source into Unity project
        run: |
          mkdir -p ${{ matrix.projectPath }}/Assets/logging

          shopt -s dotglob

          for item in *; do
            case "$item" in
              ${{ matrix.projectPath }}|.git|.github|.gitignore|.gitattributes)
                echo "Skipping $item"
                ;;
              *)
                cp -R "$item" ${{ matrix.projectPath }}/Assets/logging/
                ;;
            esac
          done

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2022.3.62f2
          projectPath: ${{ matrix.projectPath }}
          testMode: ${{ matrix.testMode }}